#

diff --git a/.github/workflows/dotnet-desktop.yml b/.github/workflows/dotnet-desktop.yml
--- a/.github/workflows/dotnet-desktop.yml
+++ b/.github/workflows/dotnet-desktop.yml
@@ -175,31 +175,31 @@ jobs:
 
           mkdir ${{env.AppxPackageDir}}
 
-          msbuild $env:Solution_Name `
-          /t:Restore `
-          /p:Configuration=${{ matrix.configuration }} `
-          /p:Platform=${{ matrix.targetplatform }}  `
-          /p:TargetFramework=net8.0-windows `
-          /p:Runtimeidentifier=win-$env:TargetPlatform `
+          # msbuild $env:Solution_Name `
+          # /t:Restore `
+          # /p:Configuration=${{ matrix.configuration }} `
+          # /p:Platform=${{ matrix.targetplatform }}  `
+          # /p:TargetFramework=net8.0-windows `
+          # /p:Runtimeidentifier=win-$env:TargetPlatform `
 
-          echo "MSBuild Restore exit code: $LASTEXITCODE"
-          if ($LASTEXITCODE -ne 0) {
-              Write-Error "MSBuild Restore failed with exit code $LASTEXITCODE"
-              exit $LASTEXITCODE
-          }
+          # echo "MSBuild Restore exit code: $LASTEXITCODE"
+          # if ($LASTEXITCODE -ne 0) {
+          #     Write-Error "MSBuild Restore failed with exit code $LASTEXITCODE"
+          #     exit $LASTEXITCODE
+          # }
 
-          msbuild $env:Wap_Project_Path/$env:Wap_Project_Path.wapproj `
-          /t:Restore `
-          /p:Configuration=${{ matrix.configuration }} `
-          /p:Platform=${{ matrix.targetplatform }}  `
-          /p:TargetFramework=net8.0-windows `
-          /p:Runtimeidentifier=win-$env:TargetPlatform `
+          # msbuild $env:Wap_Project_Path/$env:Wap_Project_Path.wapproj `
+          # /t:Restore `
+          # /p:Configuration=${{ matrix.configuration }} `
+          # /p:Platform=${{ matrix.targetplatform }}  `
+          # /p:TargetFramework=net8.0-windows `
+          # /p:Runtimeidentifier=win-$env:TargetPlatform `
 
-          echo "MSBuild Restore exit code: $LASTEXITCODE"
-          if ($LASTEXITCODE -ne 0) {
-            Write-Error "MSBuild Restore failed with exit code $LASTEXITCODE"
-            exit $LASTEXITCODE
-          }
+          # echo "MSBuild Restore exit code: $LASTEXITCODE"
+          # if ($LASTEXITCODE -ne 0) {
+          #   Write-Error "MSBuild Restore failed with exit code $LASTEXITCODE"
+          #   exit $LASTEXITCODE
+          # }
 
           msbuild $env:Wap_Project_Path/$env:Wap_Project_Path.wapproj `
           /p:AppxBundlePlatforms="${{ matrix.targetplatform}}"  `
